// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzNcO_QBlp4mfgrHm6fo2DIquQKaFjlA',
    appId: '1:932634105910:web:f575cc797081b8a29a2097',
    messagingSenderId: '932634105910',
    projectId: 'rascade-app',
    authDomain: 'rascade-app.firebaseapp.com',
    storageBucket: 'rascade-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJgGMgFLcCJO7gl3mLYHrfneurxJURck',
    appId: '1:932634105910:android:ac126df051cb74ee9a2097',
    messagingSenderId: '932634105910',
    projectId: 'rascade-app',
    storageBucket: 'rascade-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0AYiZoYe09uK45Vz-PvrBph-W8r3-kI',
    appId: '1:932634105910:ios:f364406231313a4e9a2097',
    messagingSenderId: '932634105910',
    projectId: 'rascade-app',
    storageBucket: 'rascade-app.appspot.com',
    iosBundleId: 'com.example.rascade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG0AYiZoYe09uK45Vz-PvrBph-W8r3-kI',
    appId: '1:932634105910:ios:f364406231313a4e9a2097',
    messagingSenderId: '932634105910',
    projectId: 'rascade-app',
    storageBucket: 'rascade-app.appspot.com',
    iosBundleId: 'com.example.rascade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUzNcO_QBlp4mfgrHm6fo2DIquQKaFjlA',
    appId: '1:932634105910:web:b77fb93529fca3919a2097',
    messagingSenderId: '932634105910',
    projectId: 'rascade-app',
    authDomain: 'rascade-app.firebaseapp.com',
    storageBucket: 'rascade-app.appspot.com',
  );
}
